### ISSUE TITLE
Unable to see the post being replied to.

### ISSUE THREAD

**Issue by mhverbakel** [andrey-yantsen/boterator#28]
When you use the reject button, the message indicates the post being rejected:
![image](https://cloud.githubusercontent.com/assets/11353785/24999570/56f04568-203e-11e7-9e86-313a29d70748.png)

This does not show for regular replies:
![image](https://cloud.githubusercontent.com/assets/11353785/24999582/64543106-203e-11e7-95b5-c5999776aab5.png)

**Comment by worried-networking** [comment]
What do you mean on "regular rejections"? `Reply` button? This function works only for posts sent after 10:30 GMT+3

**Comment by mhverbakel** [comment]
Ah, I see. Thanks!
