### ISSUE TITLE
Issue with boteator

### ISSUE THREAD

**Issue by EnricoTV** [andrey-yantsen/boterator#30]
Hi Andrey, 
it is occurred an issue with boteator, when arrive a message under the Reply / Ban /... buttons, the bot ask me what i want to answer to a wrong username

**Comment by worried-networking** [comment]
Hey Enrico! Can you please send me couple screenshots?

**Comment by EnricoTV** [comment]
Hi Andrey, 
maybe there is a misunderstanding, is the username highlighted in red refers to the group administrator (myself)?  Maybe this is because of the Italian translation that does not use the same (grammatical) expression. 
About this could I get you a proposal?


![screen_2017-08-24_10-15-08](https://user-images.githubusercontent.com/31281352/29656977-7ab36c4c-88b6-11e7-8a7d-f2bdbcb1dd14.jpg)

**Comment by worried-networking** [comment]
Currently there is no Italian translation, feel free to help me by translating [this file](https://github.com/andrey-yantsen/boterator/blob/master/locales/en_US/LC_MESSAGES/boterator.po).
When you're trying to reply/ban bot mentions you, in this case Telegram automatically opens `reply` interface for you, so you're not required to manually tap `reply` on bot's message.

So, it's not an issue, just misunderstanding.

**Comment by EnricoTV** [comment]
Thanks a lot Andrey! 
Have you an email address where i can write you? 
Thank you.
Enrico

**Comment by worried-networking** [comment]
You can use boterator`at`janzen`dot`su

**Comment by EnricoTV** [comment]
Thank you again
