### ISSUE TITLE
Если люди в чате с ботом отвечают, даже просто если друг другу, то бот постоянно выдает в чат:Shower Thoughts Bot: I have no idea what do you want from me. Sorry :( 

### ISSUE THREAD

**Issue by mysubcult** [andrey-yantsen/boterator#7]

**Comment by worried-networking** [comment]
Какое состояние `privacy` у бота? Нужно @BotFather написать `/setprivacy` и выбрать бота. Меня интересует последняя строка, где `Current status is:` — если там `DISABLED` — нужно включить.

**Comment by mysubcult** [comment]
Ответил в тг.
